Data:
  data_path: "./data/train.csv"
  test_data_path: "./data/test.csv"
  max_len: 256

Model:
  base_model: "tae898/emoberta-large"
  tokenizer: "tae898/emoberta-large"
  w_output_dir: "./output/"

Tranining:
  batch_size: 32
  learning_rate: 0.00003
  num_train_epochs: 10

Flag:
  do_train: 0

Wandb:
  project_name: "daycon-erc"
  run_name: "emoberta-base-ep"
