Data:
  data_path: "./data/train.csv"
  max_len: 256

Model:
  base_model: "klue/roberta-small"
  tokenizer: "klue/roberta-small"
  w_output_dir: "./output/"

Tranining:
  batch_size: 8
  learning_rate: 0.00003
  eps: 0.00000001
  num_train_epochs: 3

Flag:
  do_train: 1
  do_eval: 1
  do_test: 0
  do_demo: 0

Wandb:
  project_name: "daycon-erc"
  run_name: "base"
